/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'pavel' at '1/29/17 6:53 PM' with Gradle 2.12
 *
 * @author pavel, @date 1/29/17 6:53 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
