language: java
sudo: true

jdk:
  - oraclejdk8

cache:
 directories:
 - $HOME/.gradle/caches/
 - $HOME/.gradle/wrapper/

env:
  global:
    - GRADLE_OPTS="-Xms256m"

install: echo "skip 'gradle assemble' step"
script: ./gradlew checkScoverage --continue --info

after_success:
  - ./gradlew coveralls