/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'pavel' at '1/29/17 6:53 PM' with Gradle 2.12
 *
 * @author pavel, @date 1/29/17 6:53 PM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
